CREATE TABLE NguoiDung (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Username VARCHAR(15) NOT NULL,
	Password VARCHAR(15) NOT NULL,
	SoDienThoai VARCHAR(11),
	DiaChi VARCHAR(51),
	Email VARCHAR(20),
	HinhAnh VARCHAR(20),
	Quyen int
);

CREATE TABLE SanPham (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	MaSP VARCHAR(10),
	TenSP VARCHAR(51),
	LoaiSP INT,
	NhaSanXuatID INT,
	XuatXu VARCHAR(50),
	MoTa VARCHAR(51),
	NgayTao DATETIME,
	SoLuong int,
	HinhAnh VARCHAR(20),
	Gia DECIMAL,
	LuotXem int,
	TinhTrang binary
);

CREATE TABLE DanhMuc (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Ten VARCHAR(51)
);

CREATE TABLE NhaSanXuat (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Ten VARCHAR(51)
);

CREATE TABLE DiaChiNhanHang (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NguoiDungID INT,
	TenNguoiNhan VARCHAR(51),
	SoDienThoai VARCHAR(11),
	DiaChiGiaoHang VARCHAR(51),
);

CREATE TABLE DatHang (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserID INT,
	TongGia DECIMAL,
	LoaiGiaoHang INT,
	TinhTrang INT,
	NgayTao DATETIME,
	NgayDuKienGiaoHang DATETIME,
	DiaChiNhanHangID INT
);

CREATE TABLE ChiTietDatHang (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	DatHangID INT,
	MaSP INT,
	SoLuong INT,
	Gia DECIMAL,
	TinhTrang INT,
	NgayDuKienGiaoHang DATETIME
);